import { registerRepositoryHandlers } from './repository.handler';
import { registerProcessHandlers } from './process.handler';
import { registerPortHandlers } from './port.handler';
import { registerConfigHandlers } from './config.handler';
import { registerHealthHandlers } from './health.handler';
import { registerGitHubHandlers } from './github.handler';
import { registerGitHandlers } from './git.handler';
import { registerScaffoldHandlers } from './scaffold.handler';
import { registerCodeSearchHandlers } from './codesearch.handler';
import { registerPackageHandlers } from './packages.handler';
import { registerPackageCloneHandlers } from './package-clone.handler';
import { registerAgentHandlers } from './agent.handler';
import { registerSkillsHandlers } from './skills.handler';
import type { RepositoryService } from '../services/RepositoryService';
import type { ProcessService } from '../services/ProcessService';
import type { PortService } from '../services/PortService';
import type { ConfigService } from '../services/ConfigService';
import type { DependencyHealthService } from '../services/DependencyHealthService';
import type { GitHubService } from '../services/GitHubService';
import type { GitBranchService } from '../services/GitBranchService';
import type { ScaffoldService } from '../services/ScaffoldService';
import type { CodeSearchService } from '../services/CodeSearchService';
import type { PackageIntelligenceService } from '../services/PackageIntelligenceService';
import type { PackageCloneService } from '../services/PackageCloneService';
import type { AgentService } from '../services/AgentService';
import type { ClaudeSessionReader } from '../services/ClaudeSessionReader';
import type { SkillsService } from '../services/SkillsService';

export function registerAllHandlers(services: {
  repositoryService: RepositoryService;
  processService: ProcessService;
  portService: PortService;
  configService: ConfigService;
  healthService: DependencyHealthService;
  githubService: GitHubService;
  gitBranchService: GitBranchService;
  scaffoldService: ScaffoldService;
  codeSearchService: CodeSearchService;
  packageService: PackageIntelligenceService;
  packageCloneService: PackageCloneService;
  agentService: AgentService;
  claudeSessionReader: ClaudeSessionReader;
  skillsService: SkillsService;
}): void {
  registerRepositoryHandlers(services.repositoryService);
  registerProcessHandlers(services.processService);
  registerPortHandlers(services.portService);
  registerConfigHandlers(services.configService, services.portService);
  registerHealthHandlers(services.healthService);
  registerGitHubHandlers(services.githubService);
  registerGitHandlers(services.repositoryService, services.gitBranchService);
  registerScaffoldHandlers(services.scaffoldService);
  registerCodeSearchHandlers(services.codeSearchService);
  registerPackageHandlers(services.packageService);
  registerPackageCloneHandlers(services.packageCloneService);
  registerAgentHandlers(services.agentService, services.claudeSessionReader);
  registerSkillsHandlers(services.skillsService);
}
